apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingest
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: ingest
      version: '0.1.0'
      sourceRef:
        kind: HelmRepository
        name: nexus
        namespace: flux-system
      interval: 1m
  values:
    replicaCount: 1