apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pipeline
  namespace: default
spec:
  interval: 10s
  chart:
    spec:
      chart: pipeline
      sourceRef:
        kind: HelmRepository
        name: nexus
        namespace: flux-system
      interval: 10s