FROM trion/jenkins-docker-client:latest
USER root
RUN groupadd docker && usermod -aG docker jenkins
# RUN apt-get update
# RUN apt-get install sudo -y

# add jenkins user to sudoers, no password
# RUN echo "jenkins ALL=NOPASSWD: ALL" >> /etc/sudoers

# USER jenkins
